### ISSUE TITLE
Unable to logout via AJAX

### ISSUE THREAD

**Issue by rubinovitz** [mattupstate/flask-security#206]
When I try to logout via Ajax I get a
"The method is not allowed for the requested URL"
error.

I am trying to log out when using token authentication.

**Comment by marcosschroh** [comment]
@mattupstate You're right. But I think we need it. This is an example why:

Scenario:
You are using a token to authenticate the users

Flow:
1. User create an account (a session is created in the backend)
2. The user forgot the password. So, we need to use the endpoint that manages the Reset Password functionality (views.forgot_password). This function is decorated with @anonymous_user_required. 
3. The session is still in the backend, so we have a REDIRECT (because of the decorator) instead of the normal flow to reset the password


So, I think that decorator is fine, but we need another endpoint to manage the logout via AJAX
make sense? I can create a Pull Request to fix it.

**Comment by jirikuncar** [comment]
@marcosschroh client using tokens must not use session. Then there is no problem with the decorator around "forgot password".
