### ISSUE TITLE
How do I verify a password external to the application?

### ISSUE THREAD

**Issue by jvsteiner** [mattupstate/flask-security#299]
My use case requires another process (external to the flask app) to verify a users password.  I am using bcrypt as a backend, however, I know that HMAC is also used - since a salt must be specified even though the bcrypt algorithm supplies it's own.  I am assuming that the order is HMAC(password, SECURITY_PASSWORD_SALT, sha512) = 1st_stage, then bcrypt.generate_password_hash(1st_stage) = stored value, but I haven't been able to get a password to match external to the app framework (it works on the web side).

I also have an open SO question regarding this:
http://stackoverflow.com/questions/25136140/py-bcrypt-giving-different-hash-results-than-flask-bcrypt-possible

**Comment by nikitph** [comment]
@jvsteiner can you please explain the code here . i am not able to open beer.

HMAC.base64(password, salt, sha256) = 1st_stage
bcrypt(1st_stage)

i get to the first stage but then for bcrypt you need to do bcrypt(1st_stage, hashed_pw) yes?
really appreciate your help

**Comment by winthrop-polk** [comment]
I could use help too... trying to convert to flask from php; system uses posix permissions on ubuntu, previous created users in the shadow file have sha-512 passwords and there is a manual delay at the moment.

**Comment by jwag956** [comment]
@winthrop-polk I would never add on a question to a 5 year old thread - since it isn't clear your use case is the same.
Also - for questions - it might be better to ask on SO and use the flask-security tag (I monitor that pretty frequently).
ANd be specific - are you trying to have the flask app use the shadow passwd( i.e use standard libc calls to verify) or are you trying to import all those passwords into the flask security User model and add a password verification that works with ubuntu salted passwords?

**Comment by winthrop-polk** [comment]
Sorry bout that, I dont tend to look at dates. I ended up using the crypt module. I tried many, but they didnt always recognize the hash type which was coming from ubuntu 16.
