### ISSUE TITLE
having hmac required makes supporting legacy passwords w/o hmac impossible

### ISSUE THREAD

**Issue by protonpopsicle** [mattupstate/flask-security#320]
i've migrated user accounts from an old django app. even though I can set schemes correctly (with the undocumented SECURITY_PASSWORD_SCHEMES) like so:

```
SECURITY_PASSWORD_HASH = 'sha256_crypt'
SECURITY_PASSWORD_SCHEMES = ['sha256_crypt', 'django_pbkdf2_sha256'] 
```

old passwords won't verify because the function utils.verify_and_update_password first gets the hmac version of the password before verifying through passlib. this seems odd, a key features of passlib is the ability to support multiple encryption schemes and legacy passwords. am I missing something?

**Comment by longhotsummer** [comment]
I've been looking into this too. The way Flask-Security currently does its own HMAC handling is ... odd ... and I think non-standard in terms of passlib's expectations. Flask-Security currently calculates a secure hash twice: first by calculating the HMAC of the password and second by calling CryptContext.encrypt, which does it again. Additionally, it's using a constant salt for the first step, rather than relying on passlib to provide an automatic salt (which they recommend).

The pending patch in 72db52426f396be55540e7140b181d9a40b32ca7 as part of #324 makes a lot more sense to me because it delegates to CryptContext directly using the *password*, not the HMAC of the password. However, I suspect it's not backwards compatible since upon upgrade, old passwords wouldn't match correctly.

Any comments from anyone on the state of #324?

**Comment by longhotsummer** [comment]
Actually, it looks like 72db52426f396be55540e7140b181d9a40b32ca7 doesn't quite fix it, it still relies on `get_hmac` too much.

**Comment by danpat** [comment]
Wrapping the password in a HMAC is not necessarily a bad move, it does increase the attack surface in some scenarios (e.g. compromised database, but SECURITY_PASSWORD_SALT is kept secure).  For other scenarios, it adds little value.

However, as implemented it's tricky to do things like migrate from legacy password schemes, as originally described in the issue.  My patch was the minimum work I could think of to support my situation, I did not have a particularly large user list to migrate.

Given backwards compatibility concerns, I think the best refactoring would be to do the following:

1.  Create a custom passlib Flask-Security password scheme that simply does the HMAC with SECURITY_PASSWORD_SALT, then delegates SECURITY_PASSWORD_HASH
2.  Configure Flask-Security to use this wrapper in SECURITY_PASSWORD_SCHEMES

This would allow legacy password schemes to be added to SECURITY_PASSWORD_SCHEMES, and they would receive unmolested passwords and follow the standard passlib fallback mechanisms.  Out of the box, passwords would continue to be HMAC-ed, and in-place upgrades of Flask-Security would not break existing password databases.

**Comment by mattupstate** [comment]
I like what @danpat has suggsted.

**Comment by longhotsummer** [comment]
Would @danpat's suggestion allow a user to opt-out of the HMAC step completely? I think that's important for being able to migrate users into and out of Flask-Security.

**Comment by thadeusb** [comment]
Another related issue:

I have two applications, each which had different SECURITY_PASSWORD_SALT in their configuration. I am now needing to merge the user tables of these two applications into a single application, yet have all existing passwords continue to work without being changed. Since all of the passwords had gone through the HMAC with a different salt each, I can only select the user accounts from one of the salts going forward, leaving the other set of user accounts locked out.

Not only would an opt-out of HMAC step be nice, a way to support multiple salts, and actually the ability to remove/update the HMAC of the passwords as well during the verify and update password step.

**Comment by lnielsen** [comment]
The current behaviour is quite a show stopper for using flask-security when needing to support legacy password hashes. We basically had to resolve to monkey patching the ``utils.get_hmac`` function.

PR #378 has a minimal solution that would allow us to not monkey patch ``get_hmac``. Any chance this would get integrated. Travis is only failing because of PEP8 errors, so if @longhotsummer doesn't have the time to fix it up I'd be happy to take the PR and make Travis green.

An alternative is to simply add back in the previous behaviour (from ~2012) where you could switch on/off the use of HMAC.

**Comment by designium** [comment]
Any update on this?

**Comment by jirikuncar** [comment]
The old behaviour (from ~2012) can be enabled using `SECURITY_SINGLE_HASH=True` which effectively switches off the use of HMAC.
