### ISSUE TITLE
utils.py::get_url() should optionally send _scheme='https'

### ISSUE THREAD

**Issue by monkeysecurity** [mattupstate/flask-security#338]
I have nginx terminating SSL and proxying requests to my flask app.

Flask security is generating HTTP urls, where I really need HTTPS urls.

This occurs post-login, post-register, in emails, etc...

When flask-security is calling flask.url_for(), I would like to be able to always send these parameters:

* _external=True
* _scheme='https'

Perhaps Flask-Security could implement an optional config parameter:

OVERRIDE_FLASK_SCHEME = 'https'

Please let me know if there is a better way to do this.

Linking: 
https://github.com/Netflix/security_monkey/issues/64
https://github.com/mitsuhiko/flask/issues/773

**Comment by jonafato** [comment]
Are you saying that Flask is generating HTTP URLs when it should be generating HTTPS ones because your SSL is being terminated by nginx? Werkzeug has a middleware to address this called `ProxyFix` ([Flask-specific details](http://flask.pocoo.org/docs/0.10/deploying/wsgi-standalone/#proxy-setups)).

Flask-Security already passes `_external=True` to all links generated for email purposes.

**Comment by monkeysecurity** [comment]
I'll give that a try.  Thank you very much for the link.
