### ISSUE TITLE
Reset password error when user only has Flask-Social login

### ISSUE THREAD

**Issue by donnywals** [mattupstate/flask-security#375]
I'm not sure how this should be resolved because the password seems to be a hard dependency for the reset functionality but when a user logs in to an app with a social account (Using Flask-Social), an account is created for them. This account has an email address but no password. So when you go to the /reset page and enter the email address it throws an error: 

TypeError: must be string or buffer, not None

Debugging this shows that the md5 function is throwing this error, most likely because the user password doesn't exist? Does anybody have suggestions?

**Comment by nickretallack** [comment]
I'm also having this issue because I'm using an invitation system.  If a user attempts to reset their password before setting their password in the invitation workflow, it throws an error.

**Comment by nickretallack** [comment]
I looked at the code and it turns out the password md5 there is currently totally inconsequential.  You can take it out and it runs just fine.  So I made it ok with null passwords.  But then I realized what you really want is for it to invalidate old password reset requests when your password changes, so I actually made use of the password md5 if it's there.  Enjoy.

**Comment by jonafato** [comment]
This is fixed by #389
