### ISSUE TITLE
Wrong HTTP response code when using json tokens and AJAX  on /login

### ISSUE THREAD

**Issue by GCerar** [mattupstate/flask-security#410]
When writing Angular application I noticed, that when using authentication tokens + AJAX on login page (/login), it returns HTTP code 200, no matter if right or wrong credentials are entered. It only returns explanation such as "Specified user does not exist" and {'meta': {'code': 400, 'errors': ....}}

**Comment by nfvs** [comment]
That seems to be the case everywhere, since a 401 response requires an WWW-Authenticate header which in most browsers triggers a native user/password prompt, which is not what we usually want.

To login using AJAX you need to either create an endpoint yourself (and handle login failures with an appropriate error code) or parse the response HTML.

**Comment by GCerar** [comment]
Done that.
