### ISSUE TITLE
crash on itsdangerous

### ISSUE THREAD

**Issue by boazin** [mattupstate/flask-security#412]
I'm pretty sure it is me and not a bug - but assitance in figuring it out would be appreciated

I'm getting a crash in `itsdangerous`
```
    def derive_key(self):
        """This method is called to derive the key.  If you're unhappy with
            the default key derivation choices you can override them here.
            Keep in mind that the key derivation in itsdangerous is not intended
            to be used as a security method to make a complex key out of a short
            password.  Instead you should use large random secret keys.
            """
        salt = want_bytes(self.salt)
        if self.key_derivation == 'concat':
            return self.digest_method(salt + self.secret_key).digest()
        elif self.key_derivation == 'django-concat':
            print salt
            print self.secret_key
            return self.digest_method(salt + b'signer' +
>               self.secret_key).digest()

 TypeError: cannot concatenate 'str' and 'NoneType' objects

.env/lib/python2.7/site-packages/itsdangerous.py:336: TypeError
```

and the relevant traceback part is:
```
flask_app/mgmt_admin.py:28: in login
    return jsonify(success=True, token=user.get_auth_token())
.env/lib/python2.7/site-packages/flask_security/core.py:313: in get_auth_token
    return _security.remember_token_serializer.dumps(data)
.env/lib/python2.7/site-packages/itsdangerous.py:568: in dumps
    rv = self.make_signer(salt).sign(payload)
.env/lib/python2.7/site-packages/itsdangerous.py:414: in sign
    return value + sep + self.get_signature(value)
.env/lib/python2.7/site-packages/itsdangerous.py:349: in get_signature
    key = self.derive_key()
```

I'm defining the app pretty straight forward:
```
app.config["SECRET_KEY"] = "testing_key"
app.config["TESTING"] = True
```

from printing the values I see that:
salt: remember-salt
self.secret_key: None

**Comment by boazin** [comment]
Found the configuration problem

**Comment by rns7a1** [comment]
I'm having the same issue.  Would you mind posting the configuration problem that you found?

**Comment by boazin** [comment]
In my case I defined those 2 lines after creating the app. It should happen "before". So something like:
```
app.create_app(
        {
            "SECRET_KEY": "testing_key",
            "TESTING": True
        }
    )
```
Solved the problem

**Comment by rns7a1** [comment]
Wow.  Amazing response time and recollection.  Thanks!

On Thu, Dec 3, 2015 at 10:11 AM, boazin <notifications@github.com> wrote:

> In my case I defined those 2 lines after creating the app. It should
> happen "before". So something like:
>
> app.create_app(
>         {
>             "SECRET_KEY": "testing_key",
>             "TESTING": True
>         }
>     )
>
> Solved the problem
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mattupstate/flask-security/issues/412#issuecomment-161670059>
> .
>

-- 

------------------------------
This e-mail and any files transmitted with it may be proprietary and are 
intended solely for the use of the individual or entity to whom they are 
addressed. If you have received this e-mail in error please notify the 
sender. Please note that any views or opinions presented in this e-mail are 
solely those of the author and do not necessarily represent those of IST 
Research. The recipient should check this e-mail and any attachments for 
the presence of viruses. IST Research accepts no liability for any damage 
caused by any virus transmitted by this e-mail.

**Comment by boazin** [comment]
Luckily I managed to recreate it and figure out what I changed :)

**Comment by rns7a1** [comment]
Wow.  Thanks for the help.  I was at a loss!  It has been working fine for
me and other developers for weeks.  The CEO got that error during a demo
yesterday.  I could not recreate it!

We have:
if __name__ == "__main__":
    app.config["SECRET_KEY"] = "ITSASECRET"
    app.run(host='0.0.0.0',port=5001, debug=True)

On Thu, Dec 3, 2015 at 10:32 AM, boazin <notifications@github.com> wrote:

> Luckily I managed to recreate it and figure out what I changed :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mattupstate/flask-security/issues/412#issuecomment-161677066>
> .
>

-- 

------------------------------
This e-mail and any files transmitted with it may be proprietary and are 
intended solely for the use of the individual or entity to whom they are 
addressed. If you have received this e-mail in error please notify the 
sender. Please note that any views or opinions presented in this e-mail are 
solely those of the author and do not necessarily represent those of IST 
Research. The recipient should check this e-mail and any attachments for 
the presence of viruses. IST Research accepts no liability for any damage 
caused by any virus transmitted by this e-mail.

**Comment by rns7a1** [comment]
Whoops.  Sent too soon.

Anyway it seems like we define it before calling the app, but we don't have
the testing config.  Maybe try that.  The problem is it's so intermittent.


On Thu, Dec 3, 2015 at 10:33 AM, Rich Salaway <rich.salaway@istresearch.com>
wrote:

> Wow.  Thanks for the help.  I was at a loss!  It has been working fine for
> me and other developers for weeks.  The CEO got that error during a demo
> yesterday.  I could not recreate it!
>
> We have:
> if __name__ == "__main__":
>     app.config["SECRET_KEY"] = "ITSASECRET"
>     app.run(host='0.0.0.0',port=5001, debug=True)
>
> On Thu, Dec 3, 2015 at 10:32 AM, boazin <notifications@github.com> wrote:
>
>> Luckily I managed to recreate it and figure out what I changed :)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mattupstate/flask-security/issues/412#issuecomment-161677066>
>> .
>>
>
>

-- 

------------------------------
This e-mail and any files transmitted with it may be proprietary and are 
intended solely for the use of the individual or entity to whom they are 
addressed. If you have received this e-mail in error please notify the 
sender. Please note that any views or opinions presented in this e-mail are 
solely those of the author and do not necessarily represent those of IST 
Research. The recipient should check this e-mail and any attachments for 
the presence of viruses. IST Research accepts no liability for any damage 
caused by any virus transmitted by this e-mail.

**Comment by jonafato** [comment]
@rns7a1 The secret key should be set before the `Security` extension is initialized (i.e. before `Security(app, user_datastore)` or `security.init_app(app, user_datastore)` is called). Based on your snippet above, it looks like the key is set before `app.run` is called but after the extension is initialized.
