### ISSUE TITLE
maintain scheme?

### ISSUE THREAD

**Issue by scotchka** [mattupstate/flask-security#436]
When I try to access a @login_required route via https while not logged in, I'm redirected to the /login page, but with http scheme, as opposed to https.

A simple fix is to use something like [Flask-SSLify](https://github.com/kennethreitz/flask-sslify) to force all routes to redirect to https.

However, is it possible to keep the same scheme when going between application and Security views, so that if you start on a http url, you stay on http, and likewise for https? A use case is when the production application is https, and the dev version is http, and you want to use the same code base without keeping track of the scheme explicitly.

**Comment by jonafato** [comment]
I don't believe the scheme should be changing within Flask-Security. How are you running your application? If it's behind a proxy (e.g. nginx), are you using the `ProxyFix` wrapper?

**Comment by scotchka** [comment]
It's running on AWS ElasticBeanstalk.

**Comment by jonafato** [comment]
Is this also running with [Elastic Load Balancer](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.managing.elb.html)? If so, please see the [ELB docs](https://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/x-forwarded-headers.html) explaining the `X-Forwarded-*` headers (werkzeug's `ProxyFix` will use these correctly). Otherwise, see [these instructions](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/SSLDocker.SingleInstance.html) (listed as being for Docker, not just Python, but the nginx config is still relevant) to add the appropriate headers to your EB instance.

**Comment by jonafato** [comment]
@scotchka Do the docs I've linked to address your issue?

**Comment by scotchka** [comment]
I've forwarded your comments to our AWS expert. Thanks, and I'll close this issue.
