### ISSUE TITLE
Security object in separate module

### ISSUE THREAD

**Issue by slippers** [mattupstate/flask-security#469]
Hello,

New to python and flask and was wondering why I can't place the flask-security class instances in a separate file.  Seems the routing stops working.  

For instance if I create a file called insec.py and put the security code
```
from main import app, db
from flask.ext.security import Security, SQLAlchemyUserDatastore, \
UserMixin, RoleMixin, login_required

#declare the User and Role sqlalchemy objects

# Setup Flask-Security
user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore)
db.create_all()
# do some more user configuration
```
then from my main.py
```
#flask references

#setup the app and database

#now load security
from insec import user_datastore, security

#route stuff
```

**Comment by jonafato** [comment]
Please provide code with a full example of what's breaking, what you expect to happen, and the full stacktrace of any exceptions you experience. There's not much info here, but this looks like a circular import issue. In short, the following lines

```python
from insec import user_datastore, security  # in main.py
```
```python
from main import app, db  # in insec.py
```
conflict with each other (one needs to be imported fully before the other can import it). See [overholt](https://github.com/mattupstate/overholt) (specifically, the [factory](https://github.com/mattupstate/overholt/blob/e03209f7a059d165a9154355d090738af3159028/overholt/factory.py)) for a good example of an application using Flask-Security broken out into several modules and packages.

\* Note: because this is more of a general Python issue and not a bug or feature request for Flask-Security, this is better suited for StackOverflow than the issue tracker.

**Comment by slippers** [comment]
Thanks, I will post elsewhere.  Seeing the circular and will sort that out.
