### ISSUE TITLE
If there is an exception sending welcome email during registration, user gets 500 error

### ISSUE THREAD

**Issue by jacksonofalltrades** [mattupstate/flask-security#490]
This is a simple fix, just needs a try/except block around call to send email on user registration. The user probably doesn't even need to see an error, they just won't get a welcome email. Probably want to log an error though.

**Comment by kjaquier** [comment]
Actually the same happen when email confirmation in activated, which is more problematic.

If the user provide a non-existant email address, the account is created but an exception is raised because the confirmation email couldn't be sent. As a result, the user get an error 500 and an invalid user account is added to the database anyway.

**Comment by jirikuncar** [comment]
One can provide custom `send_mail_task` function with exception handling.
