### ISSUE TITLE
BIG bug in decorators.anonymous_user_required

### ISSUE THREAD

**Issue by lanzalibre** [mattupstate/flask-security#497]
Please, replace this code
```
def anonymous_user_required(f):
    @wraps(f)
    def wrapper(*args, **kwargs):
        if current_user.is_authenticated:
            return redirect(utils.get_url(_security.post_login_view))
        return f(*args, **kwargs)
    return wrapper
```
with 
```
def anonymous_user_required(f):
    @wraps(f)
    def wrapper(*args, **kwargs):
        if current_user.is_authenticated():
            return redirect(utils.get_url(_security.post_login_view))
        return f(*args, **kwargs)
    return wrapper
```
Note that the missing braces are a big problem because the PROPERTY current_user.is_authenticated is ALWAYS True, whereas the FUNCTION is_authenticated is not.

**Comment by phpdude** [comment]
`current_user.is_authenticated` is a function, but you missed round brackets in 1.7.5 release version.

Take a look into your source code https://github.com/mattupstate/flask-security/blob/8b1ab24341b0b4cd008ab19c76717fd8b482e81f/flask_security/decorators.py#L223

Because of this - `if <BoundFunction>` always returns True of course and when you try to register for example it tries to logout you and can't do this.

Please fix this bug and upload new version to pypi because now library doesn't work at all.

We found this bug with @lanzalibre tonight.

Thanks for your package.

**Comment by phpdude** [comment]
This is critical bug.

**Comment by phpdude** [comment]
In 1.7.4 version source code everything is fine.

https://github.com/mattupstate/flask-security/blob/1.7.4/flask_security/decorators.py#L203

**Comment by jonafato** [comment]
This is sounds like you're on an up-to-date version of Flask-Security but an old version of Flask-Login. Please upgrade your Flask-Login version, and the behavior should be fixed.

More details: in Flask-Login 0.3.0 and Flask-Security 1.7.5, `is_authenticated`, `is_active`, and `is_anonymous` changed from methods to properties. Because of this breaking change in Flask-Login, Flask-Security 1.7.5 (current stable) only supports [`Flask-Login>=0.3.0,<0.4`](https://github.com/mattupstate/flask-security/blob/301fc03b757089802659ecdab9577a1c16594a64/requirements.txt#L2). Please see the relevant changelog entries in [Flask-Login](https://github.com/maxcountryman/flask-login/blob/14e24935baf92f79233cb342dbc93c5ac546439f/CHANGES#L43-L45) and [Flask-Security](https://github.com/mattupstate/flask-security/blob/301fc03b757089802659ecdab9577a1c16594a64/CHANGES#L22). If you still notice incorrect behavior with a supported version, please post again here, and we'll get a fix in place.

**Comment by phpdude** [comment]
@jonafato Yeah, I see. @lanzalibre will check once he will wake up I think :)

0.3.2 version has properties instead of functions.

But we use Docker & pip install, so I am surprised how we can have outdated version because we today a lot of times did "pip install -r requirements.txt" and it was not cached I am sure. Maybe we had any conflict of packages installed.

**Comment by phpdude** [comment]
@jonafato Can you add deprecation warning then if installed not supported versions? I think it can help a lot of people :)

https://docs.python.org/2/library/exceptions.html#exceptions.DeprecationWarning

**Comment by lanzalibre** [comment]
I was using flask-login 0.2.11. Definitely this can be a big time consumer. Any warning as the one phpdude suggests would be of help.

**Comment by jonafato** [comment]
A deprecation warning isn't really appropriate here. The compatibility with Flask-Login < 0.3.0 is gone entirely, so there's nothing to mark as deprecated.

How was your Flask-Security version upgraded? `pip install -U Flask-Security` should upgrade Flask-Login as well, but `pip` will install incompatible versions of packages if you have them pinned as such. Forcing dependency version compliance is an issue that's beyond the scope of Flask-Security in my opinion.

It sounds like things are back to a working state with matching versions, so I'm going to close this ticket. If you experience other issues, please open a new one.
