### ISSUE TITLE
Forms are not being translated

### ISSUE THREAD

**Issue by themylogin** [mattupstate/flask-security#628]
All flask-security form fields were constructed with plain English strings. I did not understand how this is supposed to work and just hacked this: https://github.com/themylogin/flask-security/commit/6753200e3799d7fe02681c1c992965d5007604d7. Why were not form translations working out of the box?

**Comment by IngoKl** [comment]
I'm also trying to get the forms (e.g. for the login/registration) translated via Flask-BabelEx. I can't, however, get your hack to work - did you change anything else besides calling `lazy_gettext`? 

My initial thought, which until now I have not pursued, was to tap into Flask-WTFs translation routines by passing the `flask_security' domain.

**Comment by IngoKl** [comment]
I (now more thoroughly) tried to implement @themylogin's  solution, but could not get it to work. 
Merely adding `return lazy_gettext(_default_field_labels.get(key, ''))` to `get_form_field_label(key)` in forms.py did not result in any forms being translated. 

I then tried to import `_security.i18n_domain` in order to call `_security.i18n_domain.lazy_gettext(..)`. This, however, resulted in a `RuntimeError: Working outside of application context.`. 

I'm fairly certain that I'm missing something crucial. @mattupstate (and @jirikuncar) do you have any idea on how to implement form/label translations? I'd be really happy for some pointers into the right direction! 👍

**Comment by themylogin** [comment]
@IngoKl you are right, it was only half of the fix. here is the other one: https://github.com/themylogin/flask-security/commit/2891fe70ec7a45072095e112efeff82a63bbd267

**Comment by IngoKl** [comment]
@themylogin Thank you! Now it works really nicely :). Will you do a PR?
