### ISSUE TITLE
@login_required behind https proxy

### ISSUE THREAD

**Issue by lucilecoutouly** [mattupstate/flask-security#737]
Hello ,
I am triyng to use the 
```

https://rsdb.obs-nancay.fr/WRITE/instrument/getIntegre/Nrh/0

@app.route('/instrument/getIntegre/<string:name>/<string:option>', methods=['POST'])
@login_required

```

but the redirection sent is 
```
Request URL:http://rsdb.obs-nancay.fr/READ/login?next=%2Finstrument%2FgetIntegre%2FOrfees%2F0
```
i want it to be https ...

any help ...

**Comment by jonafato** [comment]
There's not a lot of info here do debug with, but this is likely due to some missing configuration. Have you seen Flask's [proxy setups documentation](http://flask.pocoo.org/docs/0.12/deploying/wsgi-standalone/#proxy-setups)? In particular, the `ProxyFix` line below is necessary for Flask to pick up the original header values from the proxy server.

```python
from werkzeug.contrib.fixers import ProxyFix
app.wsgi_app = ProxyFix(app.wsgi_app)
```

**Comment by coutouly** [comment]
Thank you, it work's great .
