### ISSUE TITLE
SQLAlchemy models outside flask app

### ISSUE THREAD

**Issue by nbob** [mattupstate/flask-security#766]
My Alchemy models extended from `sqlalchemy.ext.declarative.declarative_base()` and it is not possible to subclass from `db.Model`, because I want to use my model not only in flask app.

How can I use plain SQLAlchemy models in my flask-security application?
Or it is not possible by design?

**Comment by biomap** [comment]
db.Model is a declarative base just modified by Flask-SQLAlchemy.  Flask-Security (FS) uses regular models.  This has nothing to do with FS.  I think you need to look at contexts in the core Flask documentation.

**Comment by cthoyt** [comment]
I have worked through this scenario, and I empathize because it was not easy to figure out. There are a couple things I had to do:

1. Bind the engine to your base's metadata

```python
engine = ...
Base.metadata.bind = engine
```

This engine might come from `FlaskSQLAlchemy` so it might look like:

```python
db = SQLAlchemy(app)
Base.metadata.bind = db.engine  # FlaskSQLALchemy wraps an engine and session
...
```

2. You also have to set the base's query, which can comes from a session:

```python
session = ...
Base.query = session.query_property()
```

In practice, this can also come from your `db.session`

```python
db = SQLAlchemy(app)
...
Base.query = db.session.query_property()
```

3. Run `Base.metadata.create_all()` for good measure.
4. User and Role can inherit from your declarative base and the FS mixins, no problem :)
